# Generated by Django 5.2.8 on 2025-11-30 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('emas_to_rupiah', 'Emas → Rupiah'), ('rupiah_to_emas', 'Rupiah → Emas')], max_length=20)),
                ('price_choice', models.CharField(choices=[('BUY', 'Harga Beli'), ('SELL', 'Harga Jual')], max_length=4)),
                ('grams_input', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rupiah_input', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=18)),
                ('result_rupiah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('result_grams', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calc_gold',
                'ordering': ['-created_at'],
            },
        ),
    ]
