# Generated by Django 5.2.8 on 2025-11-30 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyFundCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_expense', models.DecimalField(decimal_places=2, max_digits=18)),
                ('months_to_save', models.IntegerField()),
                ('current_emergency_fund', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_invest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_return_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('needed_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('future_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('gap_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_fund_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calc_emergency_fund',
                'ordering': ['-created_at'],
            },
        ),
    ]
