# Generated by Django 5.2.8 on 2025-11-30 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulasiKPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_properti', models.FloatField()),
                ('penghasilan', models.FloatField()),
                ('dp_percent', models.FloatField()),
                ('tenor_bulan', models.IntegerField()),
                ('bunga_fix', models.FloatField()),
                ('periode_fix', models.IntegerField()),
                ('bunga_floating', models.FloatField()),
                ('pokok_pinjaman', models.FloatField()),
                ('total_bunga_fix', models.FloatField()),
                ('total_bunga_floating', models.FloatField()),
                ('sisa_pokok_setelah_fix', models.FloatField()),
                ('keterangan', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
