# Generated by Django 5.2.8 on 2025-11-18 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKalku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nama_lengkap',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_hp',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appKalku.user')),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='ChildEducationCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_age_years', models.DecimalField(decimal_places=2, max_digits=5)),
                ('college_years_ahead', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_tuition', models.DecimalField(decimal_places=2, max_digits=18)),
                ('inflation_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('monthly_invest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_return_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_future_need', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monthly_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.user')),
            ],
            options={
                'verbose_name': 'Child Education Calculation',
                'db_table': 'calc_child_education',
            },
        ),
        migrations.CreateModel(
            name='EmergencyFundCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_expense', models.DecimalField(decimal_places=2, max_digits=18)),
                ('target_months', models.IntegerField()),
                ('current_fund', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_invest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_return_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('months_to_reach', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.user')),
            ],
            options={
                'verbose_name': 'Emergency Fund Calculation',
                'db_table': 'calc_emergency_fund',
            },
        ),
        migrations.CreateModel(
            name='KprCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tenor_months', models.IntegerField()),
                ('fix_rate_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fix_period_months', models.IntegerField()),
                ('floating_rate_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_interest_fix', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_interest_floating', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.user')),
            ],
            options={
                'verbose_name': 'KPR Calculation',
                'db_table': 'calc_kpr',
            },
        ),
        migrations.CreateModel(
            name='MarriageCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_saving', models.DecimalField(decimal_places=2, max_digits=18)),
                ('months_to_event', models.IntegerField()),
                ('monthly_invest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_return_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gap_now', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.user')),
            ],
            options={
                'verbose_name': 'Marriage Calculation',
                'db_table': 'calc_marriage',
            },
        ),
        migrations.CreateModel(
            name='PensionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_age', models.IntegerField()),
                ('retire_age', models.IntegerField()),
                ('monthly_expense_now', models.DecimalField(decimal_places=2, max_digits=18)),
                ('inflation_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('expected_return_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('pension_years', models.IntegerField()),
                ('monthly_invest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_need_at_retire', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estimated_portfolio', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.user')),
            ],
            options={
                'verbose_name': 'Pension Calculation',
                'db_table': 'calc_pensiun',
            },
        ),
        migrations.CreateModel(
            name='VehicleCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_saving', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_invest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_return_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('needed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.user')),
            ],
            options={
                'verbose_name': 'Vehicle Calculation',
                'db_table': 'calc_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_type', models.CharField(choices=[('child_education', 'Pendidikan Anak'), ('kpr', 'KPR'), ('emergency_fund', 'Dana Darurat'), ('pension', 'Pensiun'), ('marriage', 'Pernikahan'), ('vehicle', 'Kendaraan'), ('gold', 'Emas')], default='child_education', max_length=20)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.user')),
            ],
            options={
                'verbose_name_plural': 'Calculations',
                'db_table': 'calculations',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_calculations_user'), models.Index(fields=['calculator_type', 'created_at'], name='idx_calculations_type')],
            },
        ),
        migrations.CreateModel(
            name='GoldCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('emas_to_rupiah', 'Emas ke Rupiah'), ('rupiah_to_emas', 'Rupiah ke Emas')], max_length=20)),
                ('price_choice', models.CharField(choices=[('BUY', 'Beli'), ('SELL', 'Jual')], max_length=5)),
                ('grams_input', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rupiah_input', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=18)),
                ('result_rupiah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('result_grams', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.user')),
            ],
            options={
                'verbose_name': 'Gold Calculation',
                'db_table': 'calc_gold',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_calc_gold_user')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appKalku.user')),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'db_table': 'user_roles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
