# Generated by Django 5.2.8 on 2025-11-30 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_age', models.IntegerField()),
                ('retire_age', models.IntegerField()),
                ('monthly_expense_now', models.DecimalField(decimal_places=2, max_digits=18)),
                ('inflation_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_return_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pension_years', models.IntegerField()),
                ('monthly_invest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_need_at_retire', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estimated_portfolio', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pension_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calc_pensiun',
                'ordering': ['-created_at'],
            },
        ),
    ]
