# Generated by Django 5.2.4 on 2025-12-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana_pensiun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioncalculation',
            name='is_suitable',
            field=models.BooleanField(default=False, help_text='True jika dana pensiun cukup/sesuai'),
        ),
        migrations.AddField(
            model_name='pensioncalculation',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Saran dan rekomendasi untuk user', null=True),
        ),
    ]
