# Generated by Django 5.2.8 on 2025-11-30 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_saving', models.DecimalField(decimal_places=2, max_digits=18)),
                ('months_to_event', models.IntegerField()),
                ('monthly_invest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_return_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gap_now', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='marriage_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marriage Calculation',
                'db_table': 'calc_marriage',
            },
        ),
    ]
