# Generated by Django 5.2.8 on 2025-11-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Deskripsi singkat di kartu artikel', max_length=300)),
                ('content', models.TextField(help_text='Isi artikel lengkap')),
                ('image_url', models.URLField(blank=True, help_text='URL gambar thumbnail')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artikel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
