# Generated by Django 5.2.8 on 2025-11-30 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildEducationCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_age_years', models.DecimalField(decimal_places=2, max_digits=5)),
                ('college_years_ahead', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_tuition', models.DecimalField(decimal_places=2, max_digits=18)),
                ('inflation_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('monthly_invest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_return_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_future_need', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monthly_needed', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='child_education_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child Education Calculation',
                'db_table': 'calc_child_education',
            },
        ),
    ]
